// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiccUFrNxvAOUlLGGJsZJiyPnkOEMMmIo',
    appId: '1:560022591659:web:63d5cf7a37d259d6c4ffee',
    messagingSenderId: '560022591659',
    projectId: 'crypto-list-app-35ff7',
    authDomain: 'crypto-list-app-35ff7.firebaseapp.com',
    storageBucket: 'crypto-list-app-35ff7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDybQEN0V0MiJdu2WuA_M_EY5JXbbskw',
    appId: '1:560022591659:android:f7c5ff8a151f7c56c4ffee',
    messagingSenderId: '560022591659',
    projectId: 'crypto-list-app-35ff7',
    storageBucket: 'crypto-list-app-35ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkw9lPbAjYZTyveoPF8s9QRkiQeS3hRg',
    appId: '1:560022591659:ios:cad7ca89c6ae30eac4ffee',
    messagingSenderId: '560022591659',
    projectId: 'crypto-list-app-35ff7',
    storageBucket: 'crypto-list-app-35ff7.appspot.com',
    iosBundleId: 'com.cryptoprojects.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDkw9lPbAjYZTyveoPF8s9QRkiQeS3hRg',
    appId: '1:560022591659:ios:cad7ca89c6ae30eac4ffee',
    messagingSenderId: '560022591659',
    projectId: 'crypto-list-app-35ff7',
    storageBucket: 'crypto-list-app-35ff7.appspot.com',
    iosBundleId: 'com.cryptoprojects.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiccUFrNxvAOUlLGGJsZJiyPnkOEMMmIo',
    appId: '1:560022591659:web:f50054204fc53040c4ffee',
    messagingSenderId: '560022591659',
    projectId: 'crypto-list-app-35ff7',
    authDomain: 'crypto-list-app-35ff7.firebaseapp.com',
    storageBucket: 'crypto-list-app-35ff7.appspot.com',
  );
}
